# frozen_string_literal: true

source 'https://rubygems.org'

gem 'json', '~> 2.1'
gem 'rake', '~> 12.1'
gem 'sinatra', '~> 2.2'

group :test do
  gem 'rack-test', '~> 0.7.0'
  gem 'rspec', '~> 3.0'
end

group :development, :test do
  gem 'byebug'
end
